name: ds-toolbox
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - numpy
  - pandas
  - scipy
  - pip
  - pip:
    - google-api-python-client==1.7.7
    - oauth2client==4.1.3
    - google-cloud-bigquery==1.8.1
    - fuzzywuzzy==0.17.0
    - geopy==1.19.0
    - pymongo==3.8.0
    - sshtunnel==0.1.4
    - requests>=2.22.0